# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10x8iiEYjC90yzo07Bx5vJ1025D4VUCLx
"""

import pandas as pd

housing = pd.read_csv("housing.csv")
housing.head()

"""The `NameError` indicates that `strat_train_set` is not defined. This variable is usually created when splitting the dataset into training and test sets. Let's perform a stratified split using `median_income` to ensure the training and test sets are representative of the full dataset's income distribution."""

housing.info()

housing.describe()

housing.hist(bins=50, figsize=(20,15))

housing.plot(kind="scatter", x="longitude", y="latitude", alpha=0.1)

corr_matrix = housing.corr(numeric_only=True)

corr_matrix["median_house_value"].sort_values(ascending=False)

housing["rooms_per_household"] = housing["total_rooms"] / housing["households"]
housing["bedrooms_per_room"] = housing["total_bedrooms"] / housing["total_rooms"]

housing.info()

housing.describe()

import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

housing_features = housing.drop("median_house_value", axis=1)
housing_labels = housing["median_house_value"].copy()

housing_num = housing_features.drop("ocean_proximity", axis=1)
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy="median")),
    ('std_scaler', StandardScaler()),
])

full_pipeline = ColumnTransformer([
    ("num", num_pipeline, num_attribs),
    ("cat", OneHotEncoder(), cat_attribs),
])

housing_prepared = full_pipeline.fit_transform(housing_features)

print("Data is successfully prepared!")
print("New shape of data:", housing_prepared.shape)

from sklearn.model_selection import StratifiedShuffleSplit

# 1. Income category banayein (splitting ke liye zaroori hai)
housing["income_cat"] = pd.cut(housing["median_income"],
                               bins=[0., 1.5, 3.0, 4.5, 6., np.inf],
                               labels=[1, 2, 3, 4, 5])

# 2. Data ko 80% Training aur 20% Testing mein baantein
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing, housing["income_cat"]):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]

# 3. Extra column delete karein
for set_ in (strat_train_set, strat_test_set):
    set_.drop("income_cat", axis=1, inplace=True)

print("Data split ho gaya! Ab 'strat_test_set' mil jayega.")

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

# 1. Model banayein aur train karein
lin_reg = LinearRegression()
lin_reg.fit(housing_prepared, housing_labels)

# 2. Model se predictions nikalein
housing_predictions = lin_reg.predict(housing_prepared)

# 3. Model ka error (RMSE) check karein
lin_mse = mean_squared_error(housing_labels, housing_predictions)
lin_rmse = np.sqrt(lin_mse)

print("Model Training Complete!")
print("Linear Regression RMSE (Error):", lin_rmse)

from sklearn.tree import DecisionTreeRegressor

# 1. Decision Tree model ko train karein
tree_reg = DecisionTreeRegressor()
tree_reg.fit(housing_prepared, housing_labels)

# 2. Predictions aur Error (RMSE) check karein
housing_predictions = tree_reg.predict(housing_prepared)
tree_mse = mean_squared_error(housing_labels, housing_predictions)
tree_rmse = np.sqrt(tree_mse)

print("Decision Tree Training Complete!")
print("Decision Tree RMSE (Error):", tree_rmse)

from sklearn.model_selection import cross_val_score

# 1. Cross-validation run karein (10 folds)
scores = cross_val_score(tree_reg, housing_prepared, housing_labels,
                         scoring="neg_mean_squared_error", cv=10)

# 2. Scores ko positive banayein aur RMSE nikaalein
tree_rmse_scores = np.sqrt(-scores)

# 3. Result dekhein
def display_scores(scores):
    print("Scores:", scores)
    print("Mean (Average Error):", scores.mean())
    print("Standard deviation:", scores.std())

display_scores(tree_rmse_scores)

from sklearn.ensemble import RandomForestRegressor

# 1. Random Forest model ko train karein
forest_reg = RandomForestRegressor()
forest_reg.fit(housing_prepared, housing_labels)

# 2. Training error check karein
housing_predictions = forest_reg.predict(housing_prepared)
forest_mse = mean_squared_error(housing_labels, housing_predictions)
forest_rmse = np.sqrt(forest_mse)
print("Random Forest Training RMSE:", forest_rmse)

# 3. Cross-Validation se asal performance check karein
forest_scores = cross_val_score(forest_reg, housing_prepared, housing_labels,
                                scoring="neg_mean_squared_error", cv=10)
forest_rmse_scores = np.sqrt(-forest_scores)
display_scores(forest_rmse_scores)

from sklearn.model_selection import GridSearchCV

# 1. Hyperparameters ki list banayein jinhe check karna hai
param_grid = [
    {'n_estimators': [3, 10, 30], 'max_features': [2, 4, 6, 8]},
    {'bootstrap': [False], 'n_estimators': [3, 10], 'max_features': [2, 3, 4]},
  ]

forest_reg = RandomForestRegressor()

# 2. Grid Search setup karein
grid_search = GridSearchCV(forest_reg, param_grid, cv=5,
                           scoring='neg_mean_squared_error',
                           return_train_score=True)

# 3. Best combination dhundhein
grid_search.fit(housing_prepared, housing_labels)

print("Best Parameters mil gaye:", grid_search.best_params_)

# 4. Best model ko save karein
final_model = grid_search.best_estimator_

# 1. Test set se features aur labels alag karein
X_test = strat_test_set.drop("median_house_value", axis=1)
y_test = strat_test_set["median_house_value"].copy()

# 2. Test data ko pipeline se transform karein
# Dhyan rahe: Yahan sirf transform() use karna hai, fit_transform() nahi!
X_test_prepared = full_pipeline.transform(X_test)

# 3. Final model se predictions nikaalein
final_predictions = final_model.predict(X_test_prepared)

# 4. Final Error (RMSE) check karein
final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)

print("--- FINAL RESULT ---")
print("Final RMSE on Test Set:", final_rmse)

feature_importances = grid_search.best_estimator_.feature_importances_
attributes = num_attribs + ["<1H OCEAN", "INLAND", "ISLAND", "NEAR BAY", "NEAR OCEAN"]
sorted(zip(feature_importances, attributes), reverse=True)

import joblib

# Model save karne ke liye
joblib.dump(final_model, "my_housing_model.pkl")

print("Model successfully save ho gaya!")

# Test set se pehle 5 gharon par prediction dekhne ke liye
some_data = X_test.iloc[:5]
some_labels = y_test.iloc[:5]
some_data_prepared = full_pipeline.transform(some_data)

print("Predictions:", final_model.predict(some_data_prepared))
print("Actual Labels:", list(some_labels))
